### ISSUE TITLE
Alert for queues you don't have access to

### ISSUE THREAD

**Issue by malachi26** [malachi26/ReviewQueueNotifier#3]
remove the review alerts that you don't have access to yet

**Comment by The-Quill** [comment]
Alright, so, at the moment you're checking `document.getElementsByClassName('dashboard-num')` to find all the values, which is a child element of the element that contains the class assigned to hold the value of whether you can access it.

Try to find elements that don't match `.dashboard-faded`.

**Comment by malachi26** [comment]
Done.  Check out `ReviewQueueNotification.next.user.js`
