### ISSUE TITLE
Create an icon for the app

### ISSUE THREAD

**Issue by malachi26** [malachi26/ReviewQueueNotifier#5]
needs simple icon to set it apart from the other scripts in a users arsenal

**Comment by The-Quill** [comment]
A red `R` next to an exclamation mark `!` might look cool: `R!`

**Comment by malachi26** [comment]
I just now saw this comment @The-Quill.  

I like that idea for an Icon, I will make one up when I get a chance.

if you have one made up please show it off.

**Comment by malachi26** [comment]
![New Icon](https://github.com/malachi26/ReviewQueueNotifier/raw/master/Icon2.jpg)
